import { test, expect } from './fixtures'

for (const area of ['', '/socios']) for (const width of [375, 1440]) {
  test(`Demais consultas ${area || 'Empresas'} ${width}: recolhimento e recorte aplicado`, async ({ page, evidence }) => {
    evidence.paginateEstablishments = true
    await page.setViewportSize({ width, height: 900 })
    await page.goto(`/receita-federal/cnpj${area}?modo=mapa&uf=MG&return_to=%2Fdestino`)
    const calls = () => evidence.requests.filter(row => /\/(mapa|mapa\/resultados)\/$/.test(row.path))
    const section = page.locator('.cnpj-other-queries')
    const toggle = section.locator('summary')
    const applied = page.getByLabel('Resumo dos filtros aplicados')
    await expect(applied).toContainText('Nenhum recorte aplicado')
    await page.getByRole('button', { name: 'Selecionar CNAEs', exact: true }).click()
    const cnae = page.getByRole('dialog')
    await cnae.getByRole('checkbox').first().check()
    await cnae.getByRole('button', { name: 'Confirmar', exact: true }).click()
    await page.getByRole('button', { name: 'Definir período', exact: true }).click()
    const period = page.getByRole('dialog', { name: 'Definir período' })
    await period.getByLabel('Início de atividade: de', { exact: true }).fill('2025-01-01')
    await period.getByRole('button', { name: 'Confirmar', exact: true }).click()
    await section.locator('input[name="porte"]').fill('03')
    await section.locator('input[name="matriz_filial"]').fill('1')
    await section.locator('input[name="natureza_juridica"]').fill('2062')
    await section.locator('input[name="situacao_cadastral"]').fill('2')
    if (area) {
      await section.locator('input[name="cnpj_basico"]').fill('00123456')
      await section.locator('input[name="q"]').fill('MARIA')
    }
    await toggle.focus()
    await page.keyboard.press('Enter')
    await expect(section).not.toHaveAttribute('open')
    await expect(section.getByRole('status')).toContainText('Alterações ainda não aplicadas')
    await expect(applied).toContainText('Nenhum recorte aplicado')
    await toggle.press('Enter')
    await expect(section.locator('input[name="porte"]')).toHaveValue('03')
    await expect(page.getByLabel('Resumo do período')).toContainText('01/01/2025')
    await toggle.click()
    expect(calls()).toHaveLength(0)
    await page.getByRole('button', { name: 'Aplicar filtros', exact: true }).click()
    await expect.poll(() => calls().length).toBe(2)
    for (const call of calls()) {
      expect(call.params).toMatchObject({ uf: 'MG', cnaes: '0010100', atividade_escopo: 'principal', inicio_atividade_de: '2025-01-01', porte: '03', matriz_filial: '1', natureza_juridica: '2062', situacao_cadastral: '2' })
      if (area) expect(call.params).toMatchObject({ cnpj_basico: '00123456', q: 'MARIA' })
    }
    // Applying remounts the form from the URL; collapse its restored section.
    await toggle.click()
    await expect(applied).toContainText('Aplicado: 1 CNAEs: 0010100')
    await expect(applied).toContainText('Porte: 03')
    await expect(section.getByRole('status')).toContainText('Sem alterações pendentes')
    await toggle.click()
    await section.locator('input[name="porte"]').fill('01')
    await toggle.click()
    await expect(applied).toContainText('Porte: 03')
    await expect(section.getByRole('status')).toContainText('Alterações ainda não aplicadas')
    const resultsTrigger = page.getByRole('button', { name: 'Ver estabelecimentos', exact: true })
    if (await resultsTrigger.count()) await resultsTrigger.click()
    await page.getByRole('button', { name: 'Próxima', exact: true }).click()
    if (await resultsTrigger.count()) await page.locator('.map-results-dialog').getByRole('button', { name: 'Fechar', exact: true }).click()
    await expect.poll(() => calls().length).toBe(3)
    expect(calls().at(-1)?.params.porte).toBe('03')
    await toggle.click()
    await expect(section.locator('input[name="porte"]')).toHaveValue('01')
    const dimensions = await page.evaluate(() => [document.documentElement.clientWidth, document.documentElement.scrollWidth])
    expect(dimensions[1]).toBeLessThanOrEqual(dimensions[0] + 1)
    await page.getByRole('button', { name: 'Limpar filtros', exact: true }).click()
    await expect(applied).toContainText('Nenhum recorte aplicado')
    expect(calls()).toHaveLength(3)
  })
}
