import { test, expect } from './fixtures'

for (const area of ['', '/socios']) for (const width of [375, 1440]) {
  test(`Período ${area || 'Empresas'} ${width}: rascunho, validação e aplicação`, async ({ page, evidence }) => {
    evidence.paginateEstablishments = true
    await page.setViewportSize({ width, height: 900 })
    const entry = `/receita-federal/cnpj${area}?modo=mapa&uf=MG&return_to=%2Fdestino`
    await page.goto(entry)
    const business = () => evidence.requests.filter(row => /\/(mapa|mapa\/resultados)\/$/.test(row.path))
    const trigger = page.getByRole('button', { name: 'Definir período', exact: true })
    const dialog = page.getByRole('dialog', { name: 'Definir período' })
    const start = dialog.getByLabel('Início de atividade: de', { exact: true })
    const end = dialog.getByLabel('Início de atividade: até', { exact: true })
    const eventEnd = dialog.getByLabel('Evento da situação cadastral: até', { exact: true })
    const confirm = () => dialog.getByRole('button', { name: 'Confirmar', exact: true }).click()
    await trigger.click()
    await expect(start).toBeFocused()
    await page.keyboard.press('Shift+Tab')
    await expect(dialog.getByRole('button', { name: 'Limpar', exact: true })).toBeFocused()
    await page.keyboard.press('Tab')
    await expect(start).toBeFocused()
    await start.fill('2025-02-29')
    await start.press('Enter')
    await expect(dialog).toBeVisible()
    await confirm()
    await expect(dialog.getByRole('alert')).toContainText('datas válidas')
    await expect(start).toHaveValue('2025-02-29')
    await start.fill('2025-01-01')
    await end.fill('2024-12-31')
    await confirm()
    await expect(dialog.getByRole('alert')).toContainText('posterior')
    await end.fill('')
    await eventEnd.fill('2025-12-31')
    await confirm()
    await expect(trigger).toBeFocused()
    await expect(page).toHaveURL(entry)
    await expect(page.getByLabel('Resumo do período')).toContainText('desde 01/01/2025')
    await expect(page.getByLabel('Resumo do período')).toContainText('até 31/12/2025')
    await trigger.click()
    await dialog.getByRole('button', { name: 'Limpar', exact: true }).click()
    await dialog.getByRole('button', { name: 'Cancelar', exact: true }).click()
    await trigger.click()
    await expect(start).toHaveValue('2025-01-01')
    await start.fill('2026-01-01')
    await page.keyboard.press('Escape')
    await expect(trigger).toBeFocused()
    expect(business()).toHaveLength(0)
    await page.getByRole('button', { name: 'Aplicar filtros' }).click()
    await expect.poll(() => business().length).toBe(2)
    for (const call of business()) {
      expect(call.params.inicio_atividade_de).toBe('2025-01-01')
      expect(call.params.situacao_evento_ate).toBe('2025-12-31')
      expect(call.params.cnaes).toBeUndefined()
      expect(call.params.atividade_escopo).toBeUndefined()
      expect(call.params.municipio).toBeUndefined()
      expect(call.params.situacao_cadastral).toBeUndefined()
    }
    await trigger.click()
    await start.fill('2024-01-01')
    await confirm()
    await expect(page.getByText('Alterações ainda não aplicadas.')).toBeVisible()
    const resultsTrigger = page.getByRole('button', { name: 'Ver estabelecimentos', exact: true })
    if (await resultsTrigger.count()) await resultsTrigger.click()
    await page.getByRole('button', { name: 'Próxima', exact: true }).click()
    if (await resultsTrigger.count()) await page.locator('.map-results-dialog').getByRole('button', { name: 'Fechar', exact: true }).click()
    await expect.poll(() => business().length).toBe(3)
    expect(business().at(-1)?.params.inicio_atividade_de).toBe('2025-01-01')
    await expect(page.getByLabel('Resumo do período')).toContainText('01/01/2024')
    await trigger.click()
    await dialog.getByRole('button', { name: 'Limpar', exact: true }).click()
    await confirm()
    await page.getByRole('button', { name: 'Aplicar filtros' }).click()
    expect(business()).toHaveLength(3)
    await expect(page.getByLabel('Resumo do período')).toContainText('Nenhum limite')
    await page.reload()
    await expect(page.getByLabel('Resumo do período')).toContainText('01/01/2025')
    await expect.poll(() => business().length).toBe(5)
    const dimensions = await page.evaluate(() => [document.documentElement.clientWidth, document.documentElement.scrollWidth])
    expect(dimensions[1]).toBeLessThanOrEqual(dimensions[0] + 1)
    await page.getByRole('button', { name: 'Limpar filtros', exact: true }).click()
    await expect(page.getByLabel('Resumo do período')).toContainText('Nenhum limite')
  })
}

for (const area of ['', '/socios']) {
  test(`Período ${area || 'Empresas'}: URLs bloqueadas, combinação e histórico`, async ({ page, evidence }) => {
    const base = `/receita-federal/cnpj${area}?modo=mapa`
    const business = () => evidence.requests.filter(row => /\/(mapa|mapa\/resultados)\/$/.test(row.path))
    for (const suffix of ['&inicio_atividade_de=2025-01-01', '&uf=MG&situacao_evento_ate=2025-02-30', '&uf=MG&inicio_atividade_de=2025-01-01&inicio_atividade_de=2025-02-01']) {
      await page.goto(base + suffix)
      await expect(page.getByRole('button', { name: 'Definir período' })).toBeVisible()
      await expect(page.getByText(/Nenhum recorte aplicado|parâmetros repetidos|datas válidas/).first()).toBeVisible()
      expect(business()).toHaveLength(0)
    }
    const entry = base + '&uf=MG&municipio=4123&cnaes=0010100,6201501&atividade_escopo=principal&inicio_atividade_de=2025-01-01&inicio_atividade_ate=2025-12-31&situacao_evento_de=2025-06-01&situacao_evento_ate=2025-08-01&situacao_cadastral=2&page=2&return_to=%2Fdestino'
    await page.goto(entry)
    await expect.poll(() => business().length).toBe(2)
    const [map, list] = business()
    for (const key of ['uf', 'municipio', 'cnaes', 'atividade_escopo', 'inicio_atividade_de', 'inicio_atividade_ate', 'situacao_evento_de', 'situacao_evento_ate', 'situacao_cadastral']) expect(map.params[key]).toBe(list.params[key])
    await page.getByRole('button', { name: 'Definir período' }).click()
    const dialog = page.getByRole('dialog', { name: 'Definir período' })
    await dialog.getByLabel('Início de atividade: de', { exact: true }).fill('2024-01-01')
    await dialog.getByRole('button', { name: 'Confirmar', exact: true }).click()
    expect(business()).toHaveLength(2)
    await page.getByRole('button', { name: 'Aplicar filtros', exact: true }).click()
    await expect.poll(() => business().length).toBe(4)
    expect(new URL(page.url()).searchParams.get('page')).toBe('1')
    expect(new URL(page.url()).searchParams.get('return_to')).toBe('/destino')
    await page.goBack()
    await expect(page).toHaveURL(entry)
    await expect(page.getByLabel('Resumo do período')).toContainText('01/01/2025')
    await page.getByRole('button', { name: 'Definir período' }).click()
    await dialog.getByRole('button', { name: 'Limpar', exact: true }).click()
    await dialog.getByRole('button', { name: 'Confirmar', exact: true }).click()
    await page.getByRole('button', { name: 'Aplicar filtros', exact: true }).click()
    await expect.poll(() => business().filter(row => row.params.cnaes && !row.params.inicio_atividade_de).length).toBe(2)
    expect(new URL(page.url()).searchParams.get('cnaes')).toBe('0010100,6201501')
    expect(new URL(page.url()).searchParams.get('municipio')).toBe('4123')
  })
}
