import { useQuery } from '@tanstack/react-query'
import { FormEvent } from 'react'
import { Link, useSearchParams } from 'react-router'
import { cnpjApi } from '../api/receita-federal/cnpj/client'
import { adaptPage } from '../api/receita-federal/cnpj/pagination'
import type { CompanyFilters, PageSize } from '../api/receita-federal/cnpj/types'
import { Pagination } from '../components/pagination'; import { Empty, QueryError } from '../components/query-state'; import { digits } from '../utils/format'
export function CompaniesPage() {
 const [search,setSearch]=useSearchParams(); const submitted=search.has('buscar'); const page=Number(search.get('page')||1); const pageSize=Number(search.get('page_size')||10) as PageSize
 const params:CompanyFilters={cnpj_basico:search.get('cnpj_basico')||undefined,razao_social:search.get('razao_social')||undefined,razao_social_modo:search.get('razao_social_modo')||'contendo',page,page_size:pageSize}
 const query=useQuery({queryKey:['cnpj','companies',params],queryFn:({signal})=>cnpjApi.companies(params,signal),enabled:submitted}); const view=query.data&&adaptPage(query.data,page,pageSize)
 const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const data=new FormData(e.currentTarget);const next=new URLSearchParams();data.forEach((v,k)=>{const value=k==='cnpj_basico'?digits(String(v)):String(v).trim();if(value)next.set(k,value)});next.set('buscar','1');next.set('page','1');setSearch(next)}
 const go=(value:number)=>{const next=new URLSearchParams(search);next.set('page',String(value));setSearch(next)}
 return <section><p className="eyebrow">RECEITA FEDERAL · CNPJ</p><h1>Empresas</h1><p className="page-intro">Busque a pessoa jurídica pela razão social ou pela raiz de oito dígitos.</p><form className="filter-card" onSubmit={submit}><div className="form-grid"><label className="wide">Razão social<input name="razao_social" defaultValue={search.get('razao_social')||''}/></label><label>Comparação<select name="razao_social_modo" defaultValue={params.razao_social_modo}><option value="contendo">Contendo</option><option value="inicio">Iniciando</option><option value="fim">Terminando</option><option value="exato">Exato</option></select></label><label>Raiz do CNPJ<input name="cnpj_basico" maxLength={8} inputMode="numeric" defaultValue={search.get('cnpj_basico')||''}/></label><label>Resultados<select name="page_size" defaultValue={pageSize}><option>10</option><option>25</option><option>50</option></select></label></div><div className="form-actions"><button>Buscar empresas</button><Link to="/receita-federal/cnpj/empresas">Limpar</Link></div></form>
 {!submitted&&<div className="state"><h2>Comece pela identificação</h2><p>Nenhuma consulta é feita antes de você buscar.</p></div>}{query.isPending&&submitted&&<div className="state" role="status">Consultando empresas…</div>}{query.isError&&<QueryError error={query.error} retry={()=>query.refetch()}/>} {view?.results.length===0&&<Empty/>}{view&&view.results.length>0&&<><div className="cards">{view.results.map(company=><article className="result-card" key={company.cnpj_basico}><div><span className="meta">CNPJ básico {company.cnpj_basico}</span><h2>{company.razao_social}</h2></div><Link className="arrow-link" to={`/receita-federal/cnpj/empresas/${company.cnpj_basico}`}>Ver empresa →</Link></article>)}</div><Pagination page={view.page} pageSize={view.pageSize} count={view.count} previous={view.hasPrevious} next={view.hasNext} onPage={go}/></>}</section>
}
